
export const job = [
  "Accompagnateur de groupes",
  "Accompagnateur en moyenne montagne",
  "Accompagnement des enfants dans leurs déplacements, des personnes âgées ou handicapées en dehors de leur domicile",
  "Activités photographiques (sauf photojournalisme ou photos d'art)",
  "Administrateur Bases de Données",
  "Administrateur Systèmes et Réseaux",
  "Administrateur",
  "Agent privé de recherche",
  "Agents commerciaux",
  "Aide relationnelle",
  "Analyste",
  "Animateur d'art",
  "Animateur, speaker",
  "Animateur-speaker",
  "Architecte d'intérieur",
  "Architecte naval",
  "Architecte",
  "Architecte",
  "Assistance informatique et Internet à domicile",
  "Assistant Chef de Projet",
  "Assistant aéroportuaire (agent de sécurité, vigile)",
  "Assistant social",
  "Attaché de presse",
  "Auteur de mots croisés",
  "Autre",
  "Bois et ameublement",
  "Bouchers",
  "Boulangers",
  "Business Analyste",
  "Capitaine expert",
  "Caricaturiste",
  "Cartographe",
  "Charcutiers-traiteurs",
  "Chargé d'enquête",
  "Charpentier",
  "Chauffeurs propriétaires de leur véhicule",
  "Chef de Projet",
  "Chefs d’établissements d’enseignement privé",
  "Chocolatiers confiseurs",
  "Ciseleur",
  "Coach sportif",
  "Coach",
  "Coiffeurs et coiffeurs à domicile",
  "Coloriste",
  "Concepteur",
  "Concessionnaires ou exploitants de toilettes ou vestiaires",
  "Conférencier",
  "Conseil artistique",
  "Conseil commercial",
  "Conseil d'entreprise",
  "Conseil de gestion",
  "Conseil de sociétés",
  "Conseil en brevet d'invention",
  "Conseil en communication",
  "Conseil en formation",
  "Conseil en management",
  "Conseil en marketing",
  "Conseil en organisation",
  "Conseil en publicité",
  "Conseil en relations publiques",
  "Conseil ergonome",
  "Conseil financier",
  "Conseil littéraire",
  "Conseil logistique",
  "Conseil médical",
  "Conseil qualité comptable",
  "Conseil scientifique",
  "Conseil scientifique",
  "Conseil social",
  "Conseil technique",
  "Consultant MOA",
  "Consultant",
  "Coordinateur de travaux",
  "Coordinateur",
  "Correspondants de presse",
  "Courtiers d’assurance maritime",
  "Courtiers en billets de loterie nationale et en bulletins de loto non titulaires d’un contrat de travail,",
  "Couvreur",
  "Créateur d'art",
  "Céramiste",
  "Designer Web",
  "Designer",
  "Dessin chirurgical",
  "Dessin de bijoux",
  "Dessin de publicité",
  "Dessinateur Industriel",
  "Dessinateur industriel",
  "Dessinateur projeteur",
  "Dessinateur technique",
  "Dessinateur",
  "Directeur Projet",
  "Directeur des Systèmes d’Information",
  "Documentaliste",
  "Décorateur conseil",
  "Décorateur ensemblier",
  "Décorateur floraux",
  "Décorateur",
  "Désinfection, désinsectisation, dératisation",
  "Développeur",
  "Ebéniste",
  "Economiste conseil",
  "Economiste de la construction",
  "Ecrivain public",
  "Educateur",
  "Electricien",
  "Emailleur",
  "Enquêteur social",
  "Entraineur d'échecs",
  "Entraineur sportif",
  "Entretien de la maison et travaux ménagers",
  "Entretien et réparation de motocycles",
  "Entretien et réparation de véhicules automobiles",
  "Ergotherapeute",
  "Esthéticienne",
  "Esthétique industrielle",
  "Etalagiste",
  "Etudes de marché",
  "Expert agrigole",
  "Expert automobiles",
  "Expert en cuir",
  "Expert en objets d'art",
  "Expert en écritures",
  "Expert forestier",
  "Expert judiciaire",
  "Expert maritime",
  "Expert pres les tribunaux",
  "Expert textiles",
  "Expert",
  "Exploitants de laveries automatiques,",
  "Exploitants d’auto-école",
  "Exploitants forestiers-négociants en bois,",
  "Fabrication d'autres produits alimentaires",
  "Fabrication de plats prêts à consommer, à emporter",
  "Feronnier d'art",
  "Formateur",
  "Formateur",
  "Garde d’enfant à domicile",
  "Graphiste",
  "Graphologue",
  "Guide de montagne",
  "Guide touristique",
  "Géobiologiste",
  "Géologue",
  "Géomètre",
  "Gérant de holding",
  "Gérant de tutelle",
  "Habillement",
  "Historien",
  "Hotesse d'exposition",
  "Huissieur de justice",
  "Infographiste",
  "Ingénieur Aéronautique",
  "Ingénieur Calcul",
  "Ingénieur Systèmes Réseaux",
  "Ingénieur Télécommunications",
  "Ingénieur commercial",
  "Ingénieur du son",
  "Ingénieur expert",
  "Ingénieur thermicien",
  "Ingénieur",
  "Installation de systèmes d'alarme et activités associées de surveillance",
  "Intermédiaires et auxiliaires du commerce assujettis à l’impôt sur le revenu dans la catégorie des BIC ou des BNC,",
  "Interprète",
  "Inventeur",
  "Inventoriste (pharmacie)",
  "Investigateur",
  "Joueur professionnel",
  "Journaliste Indépendant",
  "Journaliste d'entreprise",
  "Lecteur",
  "Licier",
  "Livraison de courses à domicile",
  "Maintenance, entretien et vigilance temporaires, à domicile, de la résidence principale et secondaire",
  "Maitre d'oeuvre",
  "Maitre-nageur",
  "Mandataires libres, non assimilés aux salariés et qui n’exercent pas leur activité pour le compte d’un membre d’une profession libérale",
  "Manipulateur d'électrocardiologie",
  "Mannequin",
  "Maquettiste",
  "Marchands de journaux en kiosques, terrasses et postes fixes,",
  "Maçon",
  "Menuisier",
  "Modèle",
  "Modéliste",
  "Moniteur de ski",
  "Moniteur de voile",
  "Moniteur",
  "Mosaiste",
  "Musicothérapeute",
  "Médecin conseil",
  "Médiateur pénal",
  "Métreur",
  "Naturaliste",
  "Naturopathe",
  "Nettoyage industriel et autres activités de nettoyage des bâtiments dont ramonage",
  "Noteur copiste",
  "Nutritionniste",
  "Ostéopathe",
  "Paysagiste",
  "Peintre sur soie",
  "Peintre",
  "Personnes qui exercent une profession mettant en pratique les sciences occultes ou parapsychologiques assujetties à la taxe professionnelle",
  "Petits travaux de jardinage, y compris les travaux de débroussaillage",
  "Photographe d'art",
  "Pigiste",
  "Pilote",
  "Placiers sur les marchés,",
  "Plombier",
  "Poissonnier",
  "Porteurs manutentionnaires non salariés,",
  "Potier",
  "Prestations de petit bricolage dites «hommes toutes mains »",
  "Professeur de danse",
  "Professeur de dessin",
  "Professeur de langues",
  "Professeur de musique",
  "Professeur de sport",
  "Professeur de tennis",
  "Professeur de yoga",
  "Professeur",
  "Prédicateur",
  "Préparation des repas à domicile, et commissions",
  "Psychanalyste",
  "Psychologue conseil",
  "Psychomotricien",
  "Psychosociologue",
  "Psychothérapeute",
  "Pâtissiers",
  "QA Manager",
  "Rafting",
  "Relieur d'art",
  "Responsable Systemes et Reseaux",
  "Restaurateur d'art",
  "Réalisateur audiovisuel",
  "Récupération de déchets triés",
  "Rédacteur technique",
  "Rédacteur",
  "Réparation d'ordinateurs et d'équipements de communication",
  "Répétiteur",
  "Scrum Master",
  "Scénographe",
  "Secrétaire à domicile",
  "Services administratifs divers",
  "Services de déménagement",
  "Skipper",
  "Software packager",
  "Soins de beauté dont le modelage esthétique de bien-être et de confort",
  "Soins d’esthétique à domicile pour les personnes dépendantes",
  "Soins et promenade d’animaux de compagnie pour les personnes dépendantes",
  "Soutien scolaire ou cours à domicile",
  "Sportif",
  "Styliste",
  "Sténotypiste de conférence",
  "Team Leader",
  "Testeur",
  "Thanatopracteurs",
  "Toilettage d'animaux de compagnie",
  "Topographe",
  "Traducteur technique",
  "Transcripteur",
  "Travaux acrobatiques",
  "Urbaniste",
  "Vendeurs de pizza",
  "Vigile",
  "Vérificateur",
  "Webmaster"
]
